name: OAuth Handler

on:
  repository_dispatch:
    types: [oauth-exchange]

jobs:
  exchange:
    runs-on: ubuntu-latest
    steps:
      - name: Exchange code for token
        id: exchange
        env:
          CLIENT_ID: ${{ secrets.APP_GH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.APP_GH_CLIENT_SECRET }}
          CODE: ${{ github.event.client_payload.code }}
        run: |
          response=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"$CODE\"}" \
            https://github.com/login/oauth/access_token)
          echo "::set-output name=token::$response"